on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v "$PWD:/mnt/repo" -w /mnt/repo i386/debian:unstable ./in-docker-build.sh
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} libgl1-mesa-dri_*_i386.deb
